import { createHash, createHmac, randomBytes, timingSafeEqual } from 'node:crypto'

/** Cookie carrying an invite-authenticated session token. */
export const SESSION_COOKIE_NAME = '__Host-dsh_invite'

const TOKEN_VERSION = 'v1'
const SIGNATURE_BYTES = 32
const NONCE_BYTES = 16
const BASE64URL = /^[A-Za-z0-9_-]+$/

/**
 * Compare a candidate invite code with the expected code.
 * SHA-256 hashes both UTF-8 inputs to fixed-length digests; only those equal-length digests are compared with timingSafeEqual.
 * @param candidate Candidate invite code.
 * @param expected Expected shared invite code.
 * @returns Whether the fixed-length digests are equal.
 */
export function inviteCodeMatches(candidate: string, expected: string): boolean {
  const candidateDigest = createHash('sha256').update(candidate, 'utf8').digest()
  const expectedDigest = createHash('sha256').update(expected, 'utf8').digest()
  return timingSafeEqual(candidateDigest, expectedDigest)
}

/**
 * Create a v1 signed session token.
 * @param secret HMAC-SHA256 signing secret.
 * @param ttlSeconds Token lifetime in seconds.
 * @param nowMs Current time in milliseconds since Unix epoch.
 * @param nonce Exactly 16 bytes of nonce data; random bytes are generated by default.
 * @returns A four-part base64url session token with an expiry in Unix seconds.
 * @throws {RangeError} If the lifetime is not a positive safe integer, the expiry cannot be represented as a safe integer, or
 * the nonce is not exactly 16 bytes.
 */
export function issueSessionToken(
  secret: string,
  ttlSeconds: number,
  nowMs = Date.now(),
  nonce: Uint8Array = randomBytes(NONCE_BYTES),
): string {
  if (!Number.isSafeInteger(ttlSeconds) || ttlSeconds <= 0) {
    throw new RangeError('session token lifetime must be a positive safe integer')
  }
  if (nonce.byteLength !== NONCE_BYTES) throw new RangeError('session token nonce must be exactly 16 bytes')
  const expiresSeconds = Math.floor(nowMs / 1000) + ttlSeconds
  if (!Number.isSafeInteger(expiresSeconds)) throw new RangeError('session token expiry must be a safe integer')
  const nonceText = Buffer.from(nonce).toString('base64url')
  const payload = `${TOKEN_VERSION}.${String(expiresSeconds)}.${nonceText}`
  const signature = createHmac('sha256', secret).update(payload, 'utf8').digest('base64url')
  return `${payload}.${signature}`
}

/**
 * Verify a v1 session token's format, canonical encoding, expiry, and signature.
 * @param token Token text, or undefined when the cookie is absent.
 * @param secret HMAC-SHA256 signing secret.
 * @param nowMs Current time in milliseconds since Unix epoch.
 * @returns True only for a canonical, correctly signed token with a future expiry; malformed, expired, and mismatched tokens return false.
 */
export function verifySessionToken(token: string | undefined, secret: string, nowMs = Date.now()): boolean {
  if (token === undefined) return false
  const parts = token.split('.')
  const [version, expiryText, nonceText, signatureText] = parts
  if (
    parts.length !== 4 || version !== TOKEN_VERSION || expiryText === undefined || nonceText === undefined || signatureText === undefined
  ) return false
  if (!/^\d+$/.test(expiryText) || !BASE64URL.test(nonceText) || !BASE64URL.test(signatureText)) return false
  const expiresSeconds = Number(expiryText)
  if (
    !Number.isSafeInteger(expiresSeconds) || String(expiresSeconds) !== expiryText ||
    expiresSeconds <= Math.floor(nowMs / 1000)
  ) return false
  const nonce = Buffer.from(nonceText, 'base64url')
  const providedSignature = Buffer.from(signatureText, 'base64url')
  if (
    nonce.length !== NONCE_BYTES || nonce.toString('base64url') !== nonceText ||
    providedSignature.length !== SIGNATURE_BYTES ||
    providedSignature.toString('base64url') !== signatureText
  ) return false
  const payload = `${TOKEN_VERSION}.${expiryText}.${nonceText}`
  const expectedSignature = createHmac('sha256', secret).update(payload, 'utf8').digest()
  return timingSafeEqual(expectedSignature, providedSignature)
}
