/** Contract tests for the single-host Alibaba Cloud deployment assets. */

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { describe, expect, it } from 'vitest'

const deploymentRoot = resolve(import.meta.dirname, '../deploy/alibaba-cloud')

function asset(name: string): string {
  return readFileSync(resolve(deploymentRoot, name), 'utf8')
}

describe('Alibaba Cloud deployment assets', () => {
  it('keeps Caddy as the only public entry point', () => {
    const caddyfile = asset('Caddyfile')

    expect(caddyfile).toMatch(/^\{\$DSH_PUBLIC_HOST\} \{/m)
    expect(caddyfile).toContain('Strict-Transport-Security "max-age=15552000"')
    expect(caddyfile).toMatch(/@invite\s+path \/__invite \/__invite\/\*/)
    expect(caddyfile).toMatch(/handle @invite \{[\s\S]*?reverse_proxy 127\.0\.0\.1:3080/)
    const guardedHandle = caddyfile.slice(caddyfile.indexOf('\thandle {\n'))
    expect(guardedHandle).toMatch(/forward_auth 127\.0\.0\.1:3080 \{/)
    expect(guardedHandle).toContain('uri /__invite/check')
    expect(guardedHandle.indexOf('forward_auth')).toBeLessThan(guardedHandle.indexOf('reverse_proxy'))
    expect(caddyfile.match(/header_up X-DSH-Invite-Client-IP \{remote_host\}/g)).toHaveLength(2)
    expect(caddyfile.match(/header_up X-Forwarded-Proto \{scheme\}/g)).toHaveLength(2)
    expect(caddyfile.match(/header_up X-Forwarded-Host \{host\}/g)).toHaveLength(2)
    expect(caddyfile).not.toMatch(/(?:^|\s):3080(?:\s|$)/m)
    expect(caddyfile).not.toContain(';')
  })

  it('runs one hardened loopback-only DSH service', () => {
    const unit = asset('mydsh.service')

    expect(unit).toContain('Wants=network-online.target')
    expect(unit).toContain('After=network-online.target')
    expect(unit).toContain('StartLimitIntervalSec=60')
    expect(unit).toContain('StartLimitBurst=5')
    expect(unit).toContain('Type=simple')
    expect(unit).toContain('User=mydsh')
    expect(unit).toContain('Group=mydsh')
    expect(unit).toContain('WorkingDirectory=/srv/mydsh/workspace')
    expect(unit).toContain('Environment=NODE_ENV=production')
    expect(unit).toContain('EnvironmentFile=/etc/mydsh/public.env')
    expect(unit).toContain('EnvironmentFile=/etc/mydsh/mydsh.env')
    expect(unit).toContain('ExecStart=/usr/bin/node /opt/mydsh/current/apps/cli/lib/bin.js web --patch /opt/mydsh/current/deploy/alibaba-cloud/invite-auth.cordis.yml --no-open --trusted-host ${DSH_PUBLIC_HOST}')
    expect(unit).toContain('Restart=on-failure')
    expect(unit).toContain('RestartSec=5s')
    expect(unit).toContain('TimeoutStopSec=30s')
    expect(unit).toContain('UMask=0077')
    expect(unit).toContain('NoNewPrivileges=true')
    expect(unit).toContain('PrivateTmp=true')
    expect(unit).toContain('ProtectSystem=strict')
    expect(unit).toContain('ProtectHome=true')
    expect(unit).toContain('ReadWritePaths=/var/lib/mydsh /srv/mydsh/workspace')
    expect(unit).toContain('WantedBy=multi-user.target')
    expect(unit).not.toMatch(/SystemCallFilter|IPAddressDeny|RestrictAddressFamilies/)
  })

  it('shares only the public hostname with Caddy', () => {
    const dropIn = asset('caddy-mydsh.conf')

    expect(dropIn).toContain('[Service]')
    expect(dropIn).toContain('EnvironmentFile=/etc/mydsh/public.env')
    expect(dropIn).not.toContain('mydsh.env')
    expect(dropIn).not.toMatch(/DSH_INVITE_(?:CODE|SESSION)_SECRET/)
  })

  it('bootstraps the host without accepting or printing secrets', () => {
    const script = asset('bootstrap-host.sh')

    expect(script).toMatch(/^#!\/usr\/bin\/env bash\nset -euo pipefail\n/)
    expect(script).toMatch(/\[\[ \$# -eq 1 \]\]/)
    expect(script).toMatch(/\^\(\[a-z0-9\]/)
    expect(script).toContain('mktemp -d')
    expect(script).toContain('trap cleanup EXIT')
    expect(script).not.toContain('set -x')
    expect(script).toContain('https://deb.nodesource.com/setup_24.x')
    expect(script).toMatch(/bash .*nodesource/)
    expect(script).toContain('https://dl.cloudsmith.io/public/caddy/stable/gpg.key')
    expect(script).toContain('https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt')
    expect(script).toContain('pnpm@11.7.0')
    expect(script).toMatch(/node --version[\s\S]*24/)
    expect(script).toMatch(/pnpm --version[\s\S]*11\.7\.0/)
    expect(script).toContain('openssl rand -hex 16')
    expect(script).toContain('openssl rand -hex 32')
    expect(script).toContain('if [[ ! -e /etc/mydsh/mydsh.env ]]')
    expect(script).toContain('DSH_HOME=/var/lib/mydsh')
    expect(script).toContain('DSH_INVITE_CODE_SECRET=')
    expect(script).toContain('DSH_INVITE_SESSION_SECRET=')
    expect(script).toMatch(/install -d -o root -g root -m 0755 \/opt\/mydsh\/releases \/etc\/mydsh/)
    expect(script).toContain('install -d -o mydsh -g mydsh -m 0700 /var/lib/mydsh')
    expect(script).toContain('install -d -o mydsh -g mydsh -m 0750 /srv/mydsh/workspace /var/cache/mydsh-pnpm')
    expect(script).toMatch(/caddy validate --config \/etc\/caddy\/Caddyfile --adapter caddyfile/)
    expect(script).toContain('systemctl enable caddy')
    expect(script).toContain('systemctl restart caddy')
    expect(script).not.toMatch(/systemctl (?:enable|start|restart).*mydsh/)
    expect(script).toContain('Managed by DeepSeek Harness Alibaba Cloud deployment')
    expect(script).toContain('.pre-mydsh')
    expect(script).toContain("printf 'DSH_INVITE_CODE_SECRET=%s\\n' \"$invite_code\"")
    expect(script).toMatch(/printf 'DSH_INVITE_SESSION_SECRET=%s\\n' "\$session_secret"\n  \} >"\$private_env_tmp"/)
    expect(script).not.toMatch(/(?:invite_code|session_secret)[^\n]*(?:\/dev\/stdout|>&2)/i)
  })

  it('publishes immutable releases and rolls back failed health checks', () => {
    const script = asset('deploy-release.sh')

    expect(script).toMatch(/^#!\/usr\/bin\/env bash\nset -euo pipefail\n/)
    expect(script).toMatch(/\[\[ \$# -eq 2 \]\]/)
    expect(script).not.toContain('set -x')
    expect(script).toContain('realpath -e --')
    expect(script).toContain('git bundle verify')
    expect(script).toContain('git check-ref-format --branch')
    expect(script).toContain('/opt/mydsh/releases/.staging.XXXXXX')
    expect(script).toContain('STAGED_BUNDLE="$STAGING_ROOT/release.bundle"')
    expect(script).toMatch(/install .*"\$BUNDLE_PATH" "\$STAGED_BUNDLE"/)
    expect(script).toMatch(/runuser -u mydsh -- git clone --branch .* --single-branch "\$STAGED_BUNDLE"/)
    expect(script).toMatch(/git .*rev-parse HEAD/)
    expect(script).toContain('pnpm install --frozen-lockfile --store-dir /var/cache/mydsh-pnpm')
    expect(script).toMatch(/vitest run packages\/host\/invite-auth\/tests/)
    expect(script).toContain('pnpm run build')
    expect(script).toContain('--dump-config')
    expect(script).toContain('chown -R root:root')
    expect(script).toContain('chmod -R go-w')
    expect(script).toContain('caddy validate --config /etc/caddy/Caddyfile --adapter caddyfile')
    expect(script).toMatch(/ln -s .*\/opt\/mydsh\/current\.next/)
    expect(script).toContain('mv -Tf /opt/mydsh/current.next /opt/mydsh/current')
    expect(script).toMatch(/for .* in \{1\.\.30\}/)
    expect(script).toContain('http://127.0.0.1:3080/__invite/login')
    expect(script).toMatch(/if health_check; then/)
    expect(script).toMatch(/rollback[\s\S]*systemctl restart mydsh/)
    expect(script).toContain('systemctl reload caddy')
    expect(script).not.toMatch(/rm -rf -- \/opt\/mydsh\/releases(?:\s|$)/m)
    expect(script).not.toMatch(/(?:echo|printf)[^\n]*DSH_INVITE_(?:CODE|SESSION)_SECRET/)
  })
})
